Pennsieve/discover-service

openapi/discover-service.yml, server/src/main/scala/com/blackfynn/discover/db/PublicFilesTable.scala, server/src/main/scala/com/blackfynn/discover/handlers/FileHandler.scala, server/src/test/scala/com/blackfynn/discover/handlers/FileHandlerSpec.scala
This change adds the source organization id to the response of the already existing `discover/packages/{sourcePackageId}/files` endpoint. It assumes that all files in a package have the same source organization.
=> Return the source organization id in lookup by package id

server/src/main/scala/com/blackfynn/discover/Server.scala, server/src/test/scala/com/blackfynn/discover/ServerRoutesSpec.scala
We would like to call the Discover `/packages` internally. This pull request allows this to happen. No service claim JWT is required since the endpoint is open to the public anyway.
=> Allow /packages endpoint to be called internally

build.sbt
This PR instructs the assembly command to ignore module-info.class files when building the fat jar.
Several Jackson jars include these files with differing content, so assembly could not de-duplicate them. But these files should not be necessary in a fat jar intended to be run with Java 8, so we're just going to exclude them.
=> Fix fat jar assembly

build.sbt, server/src/main/resources/application.conf, server/src/main/scala/com/pennsieve/discover/Server.scala, server/src/test/scala/com/pennsieve/discover/clients/S3StreamClientSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/DatasetHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/FileHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/MetricsHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/OrganizationHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/PublishHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/SearchHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/SyncHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/TagHandlerSpec.scala
This PR fixes the Akka dependency conflict introduced when we updated to Scala 2.13 by upgrading our Akka versions (as little as possible).
This project depends on service-utilities and the 2.13 version of that project is compiled against a newer version of akka-http which was causing a conflict in this project. So Akka and friends have been upgraded, not to the newest versions, but just enough to resolve the conflict.
=> Fix Akka dependency confict

openapi/discover-service-internal.yml, server/src/main/scala/com/pennsieve/discover/handlers/PublishHandler.scala, server/src/test/scala/com/pennsieve/discover/handlers/PublishHandlerSpec.scala
If ReleaseRequest.publishBucket is missing from an embargo release request, we use the default global publish bucket. Making it optional relieves the client (which for this endpoint is only the [pennsieve-api](https://github.com/Pennsieve/pennsieve-api) backend) from requiring access to the default publish bucket name.
One the other hand, in Discover we do not have access to full information about Organizations, so we need any custom publish bucket name associated with an org to be passed in as ReleaseRequest.publishBucket.
Making the ReleaseRequest request body itself optional did not seem to work. (The Guardrail generated client would send "null" instead of an empty body when given releaseRequest = None which caused the server to return a 400 Bad Request response.)
=> Make ReleaseRequest.publishBucket optional

build.sbt, server/src/main/resources/application.conf, server/src/main/scala/com/pennsieve/discover/Config.scala, server/src/main/scala/com/pennsieve/discover/Ports.scala, server/src/main/scala/com/pennsieve/discover/clients/S3StreamClient.scala, server/src/main/scala/com/pennsieve/discover/notifications/SQSNotificationHandler.scala, server/src/test/resources/application.conf, server/src/test/scala/com/pennsieve/discover/ConfigSpec.scala, server/src/test/scala/com/pennsieve/discover/DockerS3Service.scala, server/src/test/scala/com/pennsieve/discover/clients/MockS3StreamClient.scala, server/src/test/scala/com/pennsieve/discover/clients/S3StreamClientSpec.scala
Sets the requester pays header for S3 calls made by the SQSNotificationHandler as part of the publish workflow.
Update Akka & Alpakka version for Scala 2.13 to include requester pays bug fix on the server side.
For downloads we handle things differently and do not use the requester pays header.
In the external organization's AWS account: We require them to create a publish bucket access role in their account that has the necessary access to their publish bucket. They must also allow our discover-service task role to assume this role.
In our AWS account: We allow the discover-service task role to assume this external org's publish bucket access role. And we also create two parameters in the SSM parameter store. One for the bucket name and one for the publish bucket access role ARN. 
For …
=> Update discover-service for custom publish buckets

build.sbt, server/src/main/scala/com/pennsieve/discover/clients/S3StreamClient.scala, server/src/test/scala/com/pennsieve/discover/clients/S3StreamClientSpec.scala
When deployed, #23 failed when creating an StsClient because an http client builder could not be found on the classpath. 
This PR explicitly specifies UrlConnectionHttpClient.Builder when creating StsClient and other synchronous AWS clients.
I chose URLConnectionHttpClient over ApacheHttpClient for its faster start-up time given that we are not further configuring the http client. On the recommendation of this post: https://aws.amazon.com/blogs/developer/tuning-the-aws-java-sdk-2-x-to-reduce-startup-time/
(The ApacheHttpClient was already in our transitive dependencies and was used when running tests. But we might be excluding it from the artifact created by sbt-assembly via a merge strategy. Hence it's absence when actually running a deployed version.)
=> Specify http client builder for synchronous AWS clients.

openapi/discover-service-internal.yml, server/src/main/resources/application.conf, server/src/main/scala/com/pennsieve/discover/Errors.scala, server/src/main/scala/com/pennsieve/discover/clients/LambdaClient.scala, server/src/main/scala/com/pennsieve/discover/handlers/PublishHandler.scala, server/src/main/scala/com/pennsieve/discover/models/EmbargoReleaseJob.scala, server/src/main/scala/com/pennsieve/discover/models/PublishJob.scala, server/src/test/scala/com/pennsieve/discover/clients/MockLambdaClient.scala, server/src/test/scala/com/pennsieve/discover/handlers/PublishHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/models/JobEncodingSpec.scala
The various publish related requests need to include both publish and embargo bucket names.
This PR adds this to the internal endpoint requests and so requires an update to the calling code in pennsieve-api.
The PR also updates the requests sent to the AWS Lambda and State Machine services so those pipelines have access to both publish and embargo bucket names.
=> Include full publish/embargo bucket config in publish/release/unpublish requests

terraform/iam.tf, terraform/ssm.tf
Using Terraform to create the SSM parameters needed for the external-publish-buckets section of the configuration file.
=> Add SSM parameters for external-publish-buckets config.

server/src/main/scala/com/pennsieve/discover/models/DoiRedirect.scala
Given the new name for the SPARC organization on the platform.
We need to update the logic to point datasets with org SPARC or SPARC Consortium to sparc.science website
=> Sparc doi redirect

server/src/main/scala/com/pennsieve/discover/clients/S3StreamClient.scala, server/src/main/scala/com/pennsieve/discover/handlers/PublishHandler.scala
This PR just adds logging for S3 activity during published  dataset revision.
=> Extra Logging to debug S3 error during revision

server/src/main/scala/com/pennsieve/discover/clients/S3StreamClient.scala
S3 seems to be complaining about an illegal header in a particular multipart upload where we are not setting any custom headers.
This PR explicitly sets the headers to empty to avoid Akka's default headers.
=> Testing fix for revise error

build.sbt, server/src/main/scala/com/pennsieve/discover/Ports.scala, server/src/main/scala/com/pennsieve/discover/clients/S3StreamClient.scala, server/src/main/scala/com/pennsieve/discover/handlers/PublishHandler.scala, server/src/test/scala/com/pennsieve/discover/DockerMockServerService.scala, server/src/test/scala/com/pennsieve/discover/clients/MockServerS3StreamClientSpec.scala, server/src/test/scala/com/pennsieve/discover/clients/S3StreamClientSpec.scala
This PR follows on from #32 to fix additional errors with the dataset revision endpoint. 
The change in PR #32 fixes dataset revision for workspaces without a custom publish bucket configuration.
This PR fixes dataset revision for workspaces with a custom bucket configuration. The Alpakka multipart upload operation is not passing on the requester pays header in its UploadPart request, so this PR replaces that call with a simple PutObject. This should be okay since the files in question are small by their nature (banner image, readme, and file manifiest).
=> Fix dataset revision error

terraform/heroku-redirect/cloudfront.tf
`map` has been replaced by `tomap` in the version of Terraform we are using.
=> Updates for Terraform version upgrade.

server/src/main/scala/com/pennsieve/discover/db/PublicDatasetVersionsTable.scala, server/src/test/scala/com/pennsieve/discover/handlers/PublishHandlerSpec.scala
This fixes an issue where if the publish state machine fails, the original draft DOI is being replaced by a new DOI when the publish is retried.
The new DOI is created because it is already associated with a (failed) public_dataset_version row. This PR just updates the isDuplicateDoi query to take the version status into account.
=> Don't count failed version when checking if DOI is a duplicate

terraform/glue.tf
Adds an `input.regex` property to the Glue table definition in Terraform. Value matches the `input.regex` from the old create table script.
Should fix this error seen when hitting the `/metrics/dataset/athena/download/sync` in non-prod.
```
GENERIC_INTERNAL_ERROR: SerDeException thrown initializing deserializer org.apache.hadoop.hive.serde2.RegexSerDe. Cause: This table does not have serde property "input.regex"!
```
=> Add input.regex to S3 logs Glue table definition

terraform/glue.tf
Fixes the Terraform Glue table definition for the S3 logs. Missing column was causing the below error in non-prod.
```
HIVE_CURSOR_ERROR: Number of matching groups doesn't match the number of columns
```
=> Fix Glue table definition

terraform/glue.tf
Terraform did not seem to understand that the Glue Table resource depended on the Glue DB resource, so attempting to make it clearer by referring to the DB resource in the table resource.
=> Fix Glue DB and table definitions

terraform/athena.tf, terraform/glue.tf
There was an existing Athena DB resource defined which was conflicting with the new Glue DB resource definition when running apply.
=> Remove redundant Glue DB definition

server/src/main/scala/com/pennsieve/discover/notifications/SQSNotificationHandler.scala, server/src/test/scala/com/pennsieve/discover/notifications/SQSNotificationHandlerSpec.scala
Do not delete `output.json` on **Notify  Success** stage
=> Publishing 5.0 feature - defer delete of intermediate files

server/src/main/scala/com/pennsieve/discover/handlers/DatasetHandler.scala, server/src/main/scala/com/pennsieve/discover/models/FileDownloadDTO.scala
- get file: correctly form S3 path for 5x published datasets (does not include version id)
- manifest of files download: provide S3 VersionId to PreSigner
=> Publishing 5.0 feature - fix API endpoints

server/src/main/scala/com/pennsieve/discover/clients/LambdaClient.scala, server/src/main/scala/com/pennsieve/discover/handlers/PublishHandler.scala, server/src/main/scala/com/pennsieve/discover/models/S3CleanupStage.scala, server/src/main/scala/com/pennsieve/discover/notifications/SQSNotificationHandler.scala, server/src/test/scala/com/pennsieve/discover/clients/MockLambdaClient.scala, server/src/test/scala/com/pennsieve/discover/handlers/PublishHandlerSpec.scala
At the end of a successful Publishing, invoke S3 Clean Lambda with 'Tidy' action to delete publishing intermediate files.
=> Publishing 5.0 feature - invoke S3 Clean with 'Tidy'

openapi/discover-service.yml
- updated OpenAPI spec
- include `s3Version` property on `#/components/schemas/File`
=> Publishing 5.0: add s3Version to API responses including File type

server/src/main/scala/com/pennsieve/discover/db/PublicFileVersionsTable.scala, server/src/main/scala/com/pennsieve/discover/db/PublicFilesTable.scala, server/src/main/scala/com/pennsieve/discover/db/package.scala, server/src/test/scala/com/pennsieve/discover/db/PublicFilesMapperSpec.scala
This PR updates our ltree label creation method avoid having instances of `+` and `/` in our labels and instead use `_`(underscore) and `__`(double underscore) respectively.
Our current method of creating ltree labels is to Base64 encode each path component. This can result in a label containing `+` or `/`, but this causes a Postgres syntax error since those characters are not allowed in labels.
Since `_` is a legal ltree label character that is not a valid Base64 encoding character, the replacements should be unambiguous and backwards compatible. 
(Apparently, there is a Base64 variant that uses `-` and `_` instead of `+` and `/`, but our version of Postgres does not allow `-` in ltree labels either, so that is not currently an option. However, later versions of Postgres do allow …
=> Ensure ltree labels do not contain illegal characters

server/src/main/scala/com/pennsieve/discover/clients/S3StreamClient.scala, server/src/test/scala/com/pennsieve/discover/handlers/PublishHandlerSpec.scala
The `NewFiles` object created by the `S3StreamClient` was expanded to include the **changelog** `FileManifest`, however the `.asList()` method on the class was not including it. Its absence in the list was preventing the **changelog** being added to the `public_file_versions` table for the revision, and thus it was not present when the **browse** API endpoint was used.
The fix is to include the `changelog` in the result of the `.asList()` method
```scala
case class NewFiles(
banner: FileManifest,
readme: FileManifest,
manifest: FileManifest,
changelog: FileManifest
) {
def asList = List(banner, readme, manifest, changelog)
}
```
=> Fix Discover include changelog in revision

Jenkinsfile, server/src/main/resources/application.conf, server/src/main/scala/com/pennsieve/discover/Config.scala, server/src/main/scala/com/pennsieve/discover/db/PublicFileVersionsTable.scala, server/src/main/scala/com/pennsieve/discover/handlers/FileHandler.scala, server/src/main/scala/com/pennsieve/discover/handlers/PublishHandler.scala, server/src/main/scala/com/pennsieve/discover/models/FileTreeNode.scala, server/src/test/resources/config-with-external-buckets.conf, server/src/test/resources/config-without-external-buckets.conf, server/src/test/scala/com/pennsieve/discover/ServerRoutesSpec.scala, server/src/test/scala/com/pennsieve/discover/ServiceSpecHarness.scala, server/src/test/scala/com/pennsieve/discover/TestUtilities.scala, server/src/test/scala/com/pennsieve/discover/clients/MockServerS3StreamClientSpec.scala, server/src/test/scala/com/pennsieve/discover/clients/S3StreamClientSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/FileHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/PublishHandlerSpec.scala, terraform/ssm.tf
Discover Service updates
- set Publishing 5.0 as the default workflow
- add default S3 Buckets for Publishing 5.0 workflow
- fix Get File by Source Package Id to work with Publishing 5.0 workflow datasets
- update external-buckets-config to point to Publishing 5.0 external buckets
=> Discover Service Updates

server/src/main/scala/com/pennsieve/discover/clients/AthenaClient.scala
PR is a temporary workaround that fixes the regex used in the download-metrics-gathering Athena query.
[BUG: Fix Athena query for download metrics
](https://app.clickup.com/t/86883nhx6)
Updates the query to remove the part that looked for a version number in the request_uri and to hardcode the version number to zero.
Ultimate solution for gathering these metrics is to replace the query with another method all together. But we can use this query temporarily to keep track of downloads of the most recent version of a dataset as well as partially recovering missed metrics since the change in the request_uri with the new publishing 5.0 workflow.
=> Fix Athena query

server/src/main/scala/com/pennsieve/discover/clients/S3StreamClient.scala, server/src/test/scala/com/pennsieve/discover/clients/S3StreamClientSpec.scala
Replaces the deprecated `S3.download()` function with `S3.getObject()`.
This capability is used in the `S3StreamClient` implementation class `AlpakkaS3StreamClient`, in two places:
- `s3FileSource()` is used by several entry points to download from S3 the manifest, readme, model source, and publishing intermediate files
- `datasetFilesSource()` streams published files into a ZIP by calling `downloadRange()` to download a range of bytes at a time
Included a test to ensure that `downloadRange()` retrieves the entirety of a large file (overrode `chunkSize` to get the effect of downloading large files in multiple parts with "smaller" large files).
=> replace deprecated S3.download()

server/src/main/scala/com/pennsieve/discover/handlers/SyncHandler.scala, server/src/test/scala/com/pennsieve/discover/ServiceSpecHarness.scala, server/src/test/scala/com/pennsieve/discover/clients/MockAthenaClient.scala, server/src/test/scala/com/pennsieve/discover/handlers/SyncHandlerSpec.scala
PR modifies the `DatasetDownload` results returned by the Athena client in two ways in the`/metrics/dataset/athena/download/sync` back end.
1. Removes `DatasetDownloads` with a datasetId of zero. These appear because of a `/0/` S3 key prefix in our publish buckets used for testing but which do not correspond to datasets in Postgres and so should not be counted in the metrics.
2.The Athena query is no longer able to fill in the version of the dataset being downloaded. Instead all `DatasetDownloads` coming from the Athena client have version set to zero. So the second change is to look up the most recent version of the dataset and replace the 0 version with the that version.
Also adds a test to verify these two changes.
=> Fix: Athena Sync version mapping

server/src/main/resources/application.conf, server/src/main/scala/com/pennsieve/discover/Config.scala, server/src/main/scala/com/pennsieve/discover/Ports.scala, server/src/main/scala/com/pennsieve/discover/clients/AthenaClient.scala, server/src/test/resources/config-with-external-buckets.conf, server/src/test/resources/config-without-external-buckets.conf, server/src/test/scala/com/pennsieve/discover/ServiceSpecHarness.scala, server/src/test/scala/com/pennsieve/discover/integration/AthenaClientIntegrationSpec.scala, terraform/athena.tf, terraform/iam.tf, terraform/ssm.tf, terraform/variables.tf
- Updates Terraform with permissions and other required information to access new custom buckets for RE-JOIN and Precision.
- Updates config mapping of custom bucket -> external role to include those new custom buckets.
- Updates Athena client to include the aws-rejoin Glue table in the Athena metrics query.
=> Adds RE-JOIN and Precision buckets

openapi/discover-service-internal.yml, server/src/main/resources/db/migration/V20240725134200__add_tables_to_support_releases.sql, server/src/main/scala/com/pennsieve/discover/Server.scala, server/src/main/scala/com/pennsieve/discover/db/PublicDatasetReleaseAssetsTable.scala, server/src/main/scala/com/pennsieve/discover/db/PublicDatasetReleaseTable.scala, server/src/main/scala/com/pennsieve/discover/handlers/PublishHandler.scala, server/src/main/scala/com/pennsieve/discover/handlers/ReleaseHandler.scala, server/src/main/scala/com/pennsieve/discover/logging/DiscoverLogContext.scala, server/src/main/scala/com/pennsieve/discover/models/PublicDatasetRelease.scala, server/src/main/scala/com/pennsieve/discover/models/PublicDatasetReleaseAsset.scala, server/src/main/scala/com/pennsieve/discover/utils/BucketResolver.scala, server/src/main/scala/com/pennsieve/discover/utils/package.scala, server/src/test/scala/com/pennsieve/discover/handlers/ReleaseHandlerSpec.scala
This PR adds the first set of capability needed in the *Discover Service* to support publishing datasets of type release. 
**Database changes:**
- adding `type` column to PublicDatasets table
- adding tables to store release-specific information:
- PublicDatasetRelease: holds the release details like origin ("GitHub"), label (the tag), marker (the commit hash), and repo url
- PublicDatasetReleaseAssets: a listing of the release asset (Zip file content)
**API Changes:**
- added new endpoint that is called at the initiation of the publishing workflow
- the endpoint does the following:
- gets or creates a DOI for the publication
- creates the public dataset, public dataset version, and public dataset release database items
- adds contributors, collections, and external publications …
=> Feature/publishing datasets of type release (part 1)

server/src/main/scala/com/pennsieve/discover/handlers/PublishHandler.scala, server/src/main/scala/com/pennsieve/discover/notifications/SQSNotificationHandler.scala, server/src/test/scala/com/pennsieve/discover/handlers/PublishHandlerSpec.scala
This fixes two issues in the Discover Service:
1. [Embargo Release fails for custom buckets](https://app.clickup.com/t/86889pz4w)
- in `handleReleaseSuccess()` the **PublicDatasetVersion** is updated changing the S3 Bucket value to the publish bucket. But the previous **PublicDatasetVersion**, on which the S3 Bucket is the embargo bucket, was passed to `releaseUpdateFileVersions()`. This was causing the Discover Service to look in the wrong bucket for the Discover Release result file. 
2. [Embargo Release in the past should not Embargo](https://app.clickup.com/t/868aewrqw)
- if an embargo request is received and the release rate is not *after* today, then publish the dataset without an embargo period. Several SPARC datasets were submitted for publishing review with embargo dates, but the …
=> Discover Service - fix Embargo related bugs

server/src/main/scala/com/pennsieve/discover/clients/S3StreamClient.scala, server/src/main/scala/com/pennsieve/discover/handlers/ReleaseHandler.scala, server/src/test/scala/com/pennsieve/discover/clients/MockS3StreamClient.scala, server/src/test/scala/com/pennsieve/discover/models/JsonEncodingSpec.scala
Modified the `S3StreamClient` to return `Option[ByteString]` when performing a `GetObject()`. When S3 returns the `NoSuchKeyException` we swallow that and return a `None`.
Updated the `ReleaseHandler.finalizeRelease()` to cope with "missing" data when loading the Dataset Manifest (`manifest.json`) and the Release Asset Listing. The former case is an error, and the operation fails. The latter case is not necessarily an error. If the Zip data from GitHub is deemed invalid, then a Release Asset Listing will not be generated. In this case, we log a warning and proceed -- no failure is generated.
=> handle unavailable S3 objects

openapi/discover-service.yml, server/src/main/scala/com/pennsieve/discover/db/PublicDatasetReleaseAssetsTable.scala, server/src/main/scala/com/pennsieve/discover/handlers/DatasetHandler.scala, server/src/test/scala/com/pennsieve/discover/TestUtilities.scala, server/src/test/scala/com/pennsieve/discover/handlers/DatasetHandlerSpec.scala
Fixed the *ltree* query predicate in `PublicDatasetReleaseAssetMapper.childrenOf()` - (1) do not include the Dataset Version S3 Prefix, (2) correctly form a top-level query when path is not provided.
Added an API endpoint to get all Release Assets:
- **GET** `/datasets/{datasetId}/versions/{versionId}/assets`
=> Fix Browse Assets function

server/src/main/scala/com/pennsieve/discover/handlers/DatasetHandler.scala, server/src/test/scala/com/pennsieve/discover/handlers/DatasetHandlerSpec.scala
When the `path` query parameter is provided and the value is the empty string (""), treat path as `None`.
=> Fix Browse Assets when path is the empty string

terraform/ssm.tf
PR fixes a typo which causes the download metrics Athena query to refer to a non-existent Glue table instead of the intended table in the aws-rejoin account.
=> Fix download metrics Athena query

terraform/iam.tf
The discover-service IAM role is missing permissions for certain S3, Athena, and Glue resources of the aws-rejoin account that it needs in order to run the Athena query for the `/metrics/dataset/athena/download/sync` endpoint. This PR adds those permissions.
=> Fix Glue resource permissions for Athena query.

server/src/main/scala/com/pennsieve/discover/clients/S3StreamClient.scala, server/src/main/scala/com/pennsieve/discover/models/DoiRedirect.scala, server/src/main/scala/com/pennsieve/discover/models/WorkspaceSettings.scala, server/src/main/scala/com/pennsieve/discover/notifications/SQSNotificationHandler.scala, server/src/test/scala/com/pennsieve/discover/clients/S3StreamClientSpec.scala, server/src/test/scala/com/pennsieve/discover/models/DoiRedirectSpec.scala, terraform/iam.tf
Implements or addresses these tickets and tasks:
- [Fix revision destination S3 Key on Discover Frontend Bucket](https://app.clickup.com/t/868d0wz5v)
- [generate **Dataset Metadata V5.0** on Revision](https://app.clickup.com/t/868d3a8qk)
- [update IAM Policy to permit `sts:AssumeRole` into the AWS Open Data Account](https://app.clickup.com/t/868d1fxnu)
- [Code Repo DOI redirect URLs default to Pennsieve Discover (unless specifically customized by workspace)](https://app.clickup.com/t/868d48m3r)
=> Discover Service Updates - Sprint 83

openapi/discover-service.yml, server/src/main/scala/com/pennsieve/discover/db/PublicDatasetVersionsTable.scala, server/src/main/scala/com/pennsieve/discover/handlers/DatasetHandler.scala, server/src/test/scala/com/pennsieve/discover/TestUtilities.scala, server/src/test/scala/com/pennsieve/discover/db/PublicDatasetVersionsMapperSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/DatasetHandlerSpec.scala
Adds a new endpoint to retrieve Dataset details for a given list of DOIs. Requests will look like
`GET /datasets/doi?doi=<doi1>&doi=<doi2>&...`
The response is an object with two properties, `published` and `unpublished`. 
The value of `published` is a map from DOI to PublicDatasetDTO, the same object returned by `GET /datasets/{id}` for a published dataset.
The value of `unpublished` is a map from DOI to TombstoneDTO, the same object returned by `GET /datasets/{id}` when a dataset has been unpublished.
This is in support of the new collections-service which needed a way to get information for a batch of DOIs instead of one at a time.
=> Add /datasets/doi endpoint

.github/workflows/readme.yml
The current action `readmeio/github-readme-sync@v2` is deprecated. This PR updates us to the recommended `eadmeio/rdme@v10`
=> Update readme GitHub action

openapi/discover-service-internal.yml, openapi/discover-service.yml, server/src/main/resources/application.conf, server/src/main/resources/db/migration/V20250523132340__doi_collections_tables.sql, server/src/main/scala/com/pennsieve/discover/Config.scala, server/src/main/scala/com/pennsieve/discover/Errors.scala, server/src/main/scala/com/pennsieve/discover/db/PublicDatasetDoiCollectionDoisTable.scala, server/src/main/scala/com/pennsieve/discover/db/PublicDatasetDoiCollectionsTable.scala, server/src/main/scala/com/pennsieve/discover/db/PublicDatasetVersionsTable.scala, server/src/main/scala/com/pennsieve/discover/handlers/CollectionHandler.scala, server/src/main/scala/com/pennsieve/discover/handlers/DatasetHandler.scala, server/src/main/scala/com/pennsieve/discover/handlers/DoiCollectionHandler.scala, server/src/main/scala/com/pennsieve/discover/models/DatasetsPage.scala, server/src/main/scala/com/pennsieve/discover/models/PublicDatasetDTO.scala, server/src/main/scala/com/pennsieve/discover/models/PublicDatasetDoiCollection.scala, server/src/main/scala/com/pennsieve/discover/models/PublicDatasetDoiCollectionDoi.scala, server/src/test/resources/application.conf, server/src/test/resources/config-with-external-buckets.conf, server/src/test/resources/config-without-external-buckets.conf, server/src/test/scala/com/pennsieve/discover/ConfigSpec.scala, server/src/test/scala/com/pennsieve/discover/ServiceSpecHarness.scala, server/src/test/scala/com/pennsieve/discover/TestUtilities.scala, server/src/test/scala/com/pennsieve/discover/db/PublicDatasetVersionsMapperSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/CollectionHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/DatasetHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/DoiCollectionHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/PublishHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/SearchHandlerSpec.scala, terraform/ssm.tf, terraform/variables.tf
PR to support the publication of collections created by the [collections-service](https://github.com/Pennsieve/collections-service), sometimes called DOI collections here to distinguish from older collections concept. 
So far:
- Two new tables to hold DOI collection specific details.
- New internal endpoint `POST  /collection/{collectionId}/publish` that the collection-service will call to initiate the publication of a DOI collection.
- New internal endpoint `POST /collection/{collectionId}/finalize` to be called by collections-service once it has created and uploaded a manifest file to S3 (or failed to do so).
- New optional `doiCollection` field on `PublicDatasetDTO` that is now returned by the various `GET /dataset(s)` endpoints if the public dataset is of type `collection`.
Still to …
=> Publish DOI Collections

server/src/main/scala/com/pennsieve/discover/Server.scala
PR #125 failed to add the `DoiCollectionHandler` routes to the server. This PR is a fix for that.
=> Fix Missing DoiCollectionHandler routes

server/src/main/resources/application.conf, server/src/main/scala/com/pennsieve/discover/Config.scala, server/src/main/scala/com/pennsieve/discover/handlers/DoiCollectionHandler.scala, server/src/main/scala/com/pennsieve/discover/models/PublicDatasetDoiCollection.scala, server/src/test/resources/application.conf, server/src/test/resources/config-with-external-buckets.conf, server/src/test/resources/config-without-external-buckets.conf, server/src/test/scala/com/pennsieve/discover/ServiceSpecHarness.scala, server/src/test/scala/com/pennsieve/discover/TestUtilities.scala, server/src/test/scala/com/pennsieve/discover/db/PublicDatasetVersionsMapperSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/DatasetHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/DoiCollectionHandlerSpec.scala, terraform/ssm.tf, terraform/variables.tf
PR moves the id and name of the workspace that is used for the source org when publishing DOI collections from being hardcoded to a config setting.
For Terraform plan see https://github.com/Pennsieve/infrastructure/pull/328
=> DOI Collection id-space config

server/src/main/scala/com/pennsieve/discover/clients/S3StreamClient.scala
The method used to load dataset manifest files from S3 returns `None` both when the file cannot be found in S3 and also when an error occurs when decoding the file to a `DatasetManifest` instance. This makes it hard to figure out what the true issue is. 
PR adds a error log call to log the decoding error so this problem is not mistaken for a key-not-found issue.
=> Log manifest decoding error

build.sbt, client/src/main/scala/com/pennsieve/discover/models/DOIInformation.scala, openapi/discover-service.yml, server/src/main/scala/com/pennsieve/discover/db/PublicDatasetDoiCollectionDoisTable.scala, server/src/main/scala/com/pennsieve/discover/db/PublicDatasetDoiCollectionsTable.scala, server/src/main/scala/com/pennsieve/discover/db/PublicDatasetVersionsTable.scala, server/src/main/scala/com/pennsieve/discover/handlers/DatasetHandler.scala, server/src/main/scala/com/pennsieve/discover/handlers/DoiCollectionHandler.scala, server/src/main/scala/com/pennsieve/discover/models/DOIInformation.scala, server/src/main/scala/com/pennsieve/discover/models/PublicDatasetDTO.scala, server/src/main/scala/com/pennsieve/discover/models/PublicDatasetDoiCollection.scala, server/src/test/scala/com/pennsieve/discover/DockerPostgresService.scala, server/src/test/scala/com/pennsieve/discover/TestUtilities.scala, server/src/test/scala/com/pennsieve/discover/db/PublicDatasetDoiCollectionDoisMapperSpec.scala, server/src/test/scala/com/pennsieve/discover/db/PublicDatasetVersionsMapperSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/DatasetHandlerSpec.scala, server/src/test/scala/com/pennsieve/discover/handlers/DoiCollectionHandlerSpec.scala
Three main changes in PR are
1. Include the number of DOIs in the `DOICollectionInfo` DTO so that these counts are available in the "get datasets" response.
2. Read and save the contributors list from the DOI Collection publish request.
3. Implement `GET /datasets/{datasetId}/versions/{versionId}/dois` to get detailed info about the datasets contained in a published collection.
For 3. I wanted to return an array of json objects that could either be a PublicDatasetDTO, TombstoneDTO, or some other object if the DOI was non-Pennsieve. This would require use of `oneOf` in the OpenAPI spec which our version of Guardrail does not support. 
I tried to upgrade the Guardrail version, but could not get it to run with the newest version. So instead, this PR uses `x-scala-type` to point Guardrail to …
=> More DOI Collections publishing support

server/src/main/resources/application.conf, server/src/main/scala/com/pennsieve/discover/Config.scala, server/src/main/scala/com/pennsieve/discover/Ports.scala, server/src/main/scala/com/pennsieve/discover/clients/AthenaClient.scala, server/src/test/resources/config-with-external-buckets.conf, server/src/test/resources/config-without-external-buckets.conf, server/src/test/scala/com/pennsieve/discover/ServiceSpecHarness.scala, server/src/test/scala/com/pennsieve/discover/integration/AthenaClientIntegrationSpec.scala, terraform/athena.tf, terraform/iam.tf, terraform/ssm.tf, terraform/variables.tf
PR updates Terraform and config to include the Athena table in the SPARC AWS Open Data account that will hold its S3 access logs and the permissions required to query it. Associated infrastructure PR is https://github.com/Pennsieve/infrastructure/pull/332.
Also updates the Athena client to add this table to its union query that is used to get the download metrics for direct S3 downloads.
=> Update AthenaClient to query SPARC AWS Open Data S3 access logs.
